// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(public)/@modal/(.)search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/@modal/(.)search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/about/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/brands">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/about/fleet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/fleet">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/fleet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/about/sustainability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/sustainability">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/sustainability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/about/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/team">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/booking-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking-request">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/booking-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/brands/adventure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/adventure">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/brands/adventure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/brands/luxury/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/luxury">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/brands/luxury/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/brands/wellness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brands/wellness">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/brands/wellness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/build-tour/faqs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/build-tour/faqs">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/build-tour/faqs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/build-tour/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/build-tour/how-it-works">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/build-tour/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/build-tour/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/build-tour">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/build-tour/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/build-tour/proposal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/build-tour/proposal">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/build-tour/proposal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/destinations/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destinations/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/destinations/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/destinations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destinations">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/destinations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/destinations/region/[region]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/destinations/region/[region]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/destinations/region/[region]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/guide/best-time-to-visit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/best-time-to-visit">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/guide/best-time-to-visit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/guide/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/blog">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/guide/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/guide/regions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/regions">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/guide/regions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/inquire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inquire">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/inquire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/mice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mice">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/mice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offers">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/packages/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packages/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/packages/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packages">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/payment/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/payment/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/return-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/return-policy">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/return-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/the-masterpiece/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/the-masterpiece">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/the-masterpiece/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tours/coastal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours/coastal">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tours/coastal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tours/cultural/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours/cultural">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tours/cultural/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tours/experiences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours/experiences">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tours/experiences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tours/hill-country/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours/hill-country">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tours/hill-country/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tours/honeymoon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours/honeymoon">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tours/honeymoon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tours/wellness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours/wellness">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tours/wellness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/tours/wildlife-adventure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours/wildlife-adventure">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/tours/wildlife-adventure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/transfers/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfers/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/transfers/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/transfers/airport-concierge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfers/airport-concierge">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/transfers/airport-concierge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/transfers/cruise-rail-vip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfers/cruise-rail-vip">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/transfers/cruise-rail-vip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/transfers/evening-event-chauffeur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfers/evening-event-chauffeur">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/transfers/evening-event-chauffeur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/transfers/intercity-executive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfers/intercity-executive">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/transfers/intercity-executive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/transfers/on-demand-chauffeur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfers/on-demand-chauffeur">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/transfers/on-demand-chauffeur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/transfers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfers">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/transfers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/transfers/safari-national-park/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transfers/safari-national-park">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/transfers/safari-national-park/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin-applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin-applications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin-applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/archive">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/bookings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bookings/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/bookings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/destinations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/destinations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/destinations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/destinations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/destinations/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/destinations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/destinations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/destinations">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/destinations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/finance/invoices/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finance/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/finance/invoices/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/finance/invoices/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finance/invoices/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/finance/invoices/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/finance/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finance/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/finance/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/finance/payments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finance/payments/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/finance/payments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/finance/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/finance/payments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/finance/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/fleet/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/fleet/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/fleet/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/fleet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/fleet">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/fleet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/hotel/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/hotel/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/hotel/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/hotel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/hotel">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/hotel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/my-bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-bookings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/my-bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/my-plans/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-plans/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/my-plans/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/my-plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-plans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/my-plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notifications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notifications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notifications/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notifications/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/packages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/packages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/packages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/packages/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/packages/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/packages/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/packages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/partner-application/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partner-application">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/partner-application/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/partners/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partners/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/partners/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/partners/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partners/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/partners/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partners">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/support/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/support/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/support/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/support">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/users/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/users/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/users/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/users/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vehicles/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vehicles/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vehicles/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vehicles/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vehicles/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vehicles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vehicles/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vehicles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/return/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/return">> = Specific
  const handler = {} as typeof import("../../src/app/payment/return/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/archive/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/archive/action">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/archive/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/archive">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/csrf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/csrf">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/csrf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/mock-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mock-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/mock-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/resend-verification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/resend-verification">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/resend-verification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blocks/[blockId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blocks/[blockId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/blocks/[blockId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/booking-partners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking-partners">> = Specific
  const handler = {} as typeof import("../../src/app/api/booking-partners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/attachments/[attachmentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]/attachments/[attachmentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/attachments/[attachmentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]/attachments">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]/timeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/destinations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destinations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/destinations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/destinations/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destinations/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/destinations/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/destinations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/destinations">> = Specific
  const handler = {} as typeof import("../../src/app/api/destinations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/districts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/districts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/districts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/districts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/districts">> = Specific
  const handler = {} as typeof import("../../src/app/api/districts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/faqs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/faqs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/faqs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/faqs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/faqs">> = Specific
  const handler = {} as typeof import("../../src/app/api/faqs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/finance/receipt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/receipt">> = Specific
  const handler = {} as typeof import("../../src/app/api/finance/receipt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gallery/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/gallery/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gallery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/api/gallery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invoices/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/invoices/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/api/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/packages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/packages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/packages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/packages/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/packages/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/api/packages/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partner-requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner-requests/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/partner-requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partner-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/partner-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partner-service-blocks/[blockId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner-service-blocks/[blockId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/partner-service-blocks/[blockId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partner-service-blocks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner-service-blocks">> = Specific
  const handler = {} as typeof import("../../src/app/api/partner-service-blocks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partner-services/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner-services/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/partner-services/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partners/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/partners/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners">> = Specific
  const handler = {} as typeof import("../../src/app/api/partners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payhere/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payhere/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/payhere/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payhere/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payhere/notify">> = Specific
  const handler = {} as typeof import("../../src/app/api/payhere/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/places/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/places">> = Specific
  const handler = {} as typeof import("../../src/app/api/places/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plans">> = Specific
  const handler = {} as typeof import("../../src/app/api/plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/booking-request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/booking-request">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/booking-request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/receipts/[paymentId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/receipts/[paymentId]/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/receipts/[paymentId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/finance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/finance">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/finance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/seed-packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed-packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/seed-packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/testimonials/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/testimonials/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/testimonials/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/testimonials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/testimonials">> = Specific
  const handler = {} as typeof import("../../src/app/api/testimonials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tickets/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tickets/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/api/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trip/route/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trip/route">> = Specific
  const handler = {} as typeof import("../../src/app/api/trip/route/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vehicles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/vehicles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vehicles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/api/vehicles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
